name: Workflow / XML validate

on:
  push:
    branches: [main]
    paths:
      - "**.xml"
  pull_request:
    paths:
      - "**.xml"
  workflow_dispatch:

jobs:
  yamllint:
    name: ğŸ§¹ XML Validate
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out configuration from GitHub
        uses: actions/checkout@v6
      - name: ğŸš€ Run XML Validate
        uses: kehoecj/validate-configs-action@v4
        with:
          exclude-dirs: "MediaPortal.Tests"
          exclude-file-types: "yaml,yml"
